apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: default
type: Opaque
data:
  mongo-url: bW9uZ29kYitzcnY6Ly9zbGltYmVuZGFhbGk6WXZyNlU4QU5nZEVDSGhCN0BjbHVzdGVyMC44ZnhoeS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
