# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-node-backend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: my-node-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
